# -*- coding: utf-8 -*-
"""datitos.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXg68qPzVb79meGlEJENcnAZwBlw-CsY
"""

# Requiere: streamlit, pandas, gspread, oauth2client

import streamlit as st
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# --- CONFIGURACIÓN GOOGLE SHEETS ---
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
credentials = ServiceAccountCredentials.from_json_keyfile_name("credenciales.json", scope)
client = gspread.authorize(credentials)

# ID real de tu Google Sheet
SHEET_ID = "14FreYhyr8OQ7O6PKft2nhQRYhBI8gt-RX-dFV64Q_Og"
sheet = client.open_by_key(SHEET_ID).worksheet("Base")

# --- FUNCIONES PARA CARGAR Y GUARDAR DATOS ---
def cargar_datos():
    data = sheet.get_all_records()
    return pd.DataFrame(data)

def guardar_datos(df):
    sheet.clear()
    sheet.update([df.columns.values.tolist()] + df.values.tolist())

# --- FORMULARIO DE USUARIO ---
st.title("💘 Juego de Match de Parejas")
st.write("Completa tus datos para buscar a tu alma gemela")

nombre = st.text_input("Nombre")
edad = st.number_input("Edad", min_value=18, max_value=100)
genero = st.selectbox("Género", ["Femenino", "Masculino", "No binario"])
universidad = st.text_input("Universidad")
cumpleaños = st.date_input("Cumpleaños")
signo = st.selectbox("Signo zodiacal", ["Aries", "Tauro", "Géminis", "Cáncer", "Leo", "Virgo",
                                        "Libra", "Escorpio", "Sagitario", "Capricornio", "Acuario", "Piscis"])
altura = st.number_input("Altura (cm)", min_value=100, max_value=250)
hobbies = st.multiselect("Hobbies", ["Leer", "Bailar", "Cocinar", "Viajar", "Ver películas", "Deporte", "Arte", "Música"])
quiere_hijos = st.radio("¿Quieres tener hijos?", ["Sí", "No"])
interes = st.selectbox("¿Qué género te interesa?", ["Hombre", "Mujer", "Ambos"])
rango_edad = st.selectbox("Rango de edad preferido", ["Misma edad", "Hasta 5 años más", "Hasta 5 años menos"])
rango_altura = st.multiselect("Altura preferida", ["Misma talla", "Más alta", "Más baja"])

if st.button("Buscar pareja 💌"):
    if nombre and hobbies:
        nuevo_usuario = {
            "nombre": nombre,
            "edad": edad,
            "genero": genero,
            "universidad": universidad,
            "cumpleaños": str(cumpleaños),
            "signo": signo,
            "altura": altura,
            "hobbies": ','.join(hobbies),
            "quiere_hijos": quiere_hijos,
            "interes": interes,
            "rango_edad": rango_edad,
            "rango_altura": ','.join(rango_altura),
            "ya_tiene_match": "no"
        }

        df = cargar_datos()
        df = pd.concat([df, pd.DataFrame([nuevo_usuario])], ignore_index=True)

        # --- BÚSQUEDA DE MATCH ---
        posibles = df[df["ya_tiene_match"] == "no"].copy()
        posibles = posibles[posibles["nombre"] != nombre]

        def es_compatible(fila):
            if genero not in fila["interes"] and fila["genero"] not in interes:
                return False

            signos_compatibles = {
                "Aries": ["Leo", "Sagitario", "Géminis"],
                "Tauro": ["Virgo", "Capricornio", "Cáncer"],
                "Géminis": ["Acuario", "Libra", "Aries"],
                "Cáncer": ["Piscis", "Escorpio", "Tauro"],
                "Leo": ["Aries", "Sagitario", "Libra"],
                "Virgo": ["Tauro", "Capricornio", "Escorpio"],
                "Libra": ["Géminis", "Leo", "Acuario"],
                "Escorpio": ["Cáncer", "Piscis", "Virgo"],
                "Sagitario": ["Leo", "Aries", "Acuario"],
                "Capricornio": ["Tauro", "Virgo", "Piscis"],
                "Acuario": ["Géminis", "Libra", "Sagitario"],
                "Piscis": ["Escorpio", "Cáncer", "Capricornio"]
            }
            if signo not in signos_compatibles.get(fila["signo"], []):
                return False

            if quiere_hijos != fila["quiere_hijos"]:
                return False

            h1 = set(hobbies)
            h2 = set(fila["hobbies"].split(','))
            if len(h1.intersection(h2)) == 0:
                return False

            edad_otro = int(fila["edad"])
            if rango_edad == "Misma edad" and abs(edad - edad_otro) > 1:
                return False
            elif rango_edad == "Hasta 5 años más" and edad_otro - edad > 5:
                return False
            elif rango_edad == "Hasta 5 años menos" and edad - edad_otro > 5:
                return False

            altura_otro = int(fila["altura"])
            if "Misma talla" in rango_altura and abs(altura - altura_otro) <= 3:
                return True
            if "Más alta" in rango_altura and altura_otro > altura:
                return True
            if "Más baja" in rango_altura and altura_otro < altura:
                return True
            return False

        match = posibles[posibles.apply(es_compatible, axis=1)]

        if not match.empty:
            persona = match.iloc[0]
            st.success(f"¡Felicidades {nombre}! Has hecho match con **{persona['nombre']}** 🎉💖")
            df.loc[df["nombre"] == nombre, "ya_tiene_match"] = "sí"
            df.loc[df["nombre"] == persona["nombre"], "ya_tiene_match"] = "sí"
        else:
            st.info(f"No encontramos una pareja ideal por ahora, {nombre}. 🌸✨ Pero no pierdas la esperanza, ¡tu match perfecto puede estar a punto de aparecer!")

        guardar_datos(df)
    else:
        st.warning("Por favor, completa todos los campos obligatorios.")